name: Bug Report
description: Report incorrect behavior in the shap library
title: "BUG: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Minimal Reproducible Example
      description: >
        Please follow [this guide](https://matthewrocklin.com/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example.
      placeholder: |
        import shap

        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe or show a code example of the expected behavior.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Bug report checklist
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
          required: true
        - label: I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
        - label: I'd be interested in making a PR to fix this bug
  - type: textarea
    id: version
    attributes:
      label: Installed Versions
      description: What version of the shap library are you using?
    validations:
      required: true
